### ISSUE TITLE
New question type: file upload

### ISSUE THREAD

**Issue by plutov** [plutov/formulosity#8]
Question to upload a file, which is then uploaded to specified docker volume.

**Comment by divyansh2375** [comment]
hi i want to work on this issue

**Comment by plutov** [comment]
@jacksonwun let's start with one volume for the data. And add optional validation in Yaml. for example:

```yaml
type: file
validation:
  max_size_bytes: 123*123
  formats:
    - .jpg,
    - .jpeg
...
```
