### ISSUE TITLE
Pipe answers to other questions

### ISSUE THREAD

**Issue by plutov** [plutov/formulosity#9]

**Comment by anveshthakur** [comment]
Can I take this up @plutov

**Comment by plutov** [comment]
@anveshthakur sure, this one needs a good design so it can be scaled later.

**Comment by anveshthakur** [comment]
I will come up with something first and let you know.

**Comment by anveshthakur** [comment]
hi @plutov, I am thinking of something like this

```yaml
- type: short-text
  label: What country you wanna travel?
  name: askCountry
- type: short-text
  label: What is the capital of ${askCountry}?
  ```

So basically -
1. Assign this name property to the question in YAML file and then reference it using the name property
2. Frontend will be responsible for inserting the answer in the template string
3. In that case once we get the answer for 1 question we can check which question has that name and can fetch the answer for it?

It is a very rough Idea though as of now..

let me know what do you think about it?
